import { useState } from 'react';
import { ArrowRight, Check, ChevronDown, MapPin, Menu, Phone, Recycle, Truck, Building2, ShieldCheck, Calculator, X } from 'lucide-react';
import '@fontsource/manrope/400.css';
import '@fontsource/manrope/500.css';
import '@fontsource/manrope/600.css';
import '@fontsource/manrope/700.css';
import '@fontsource/space-grotesk/600.css';
import '@fontsource/space-grotesk/700.css';
import './styles.css';

type Metal={slug:string;name:string;tag:string;text:string};
const metals:Metal[]=[
 {slug:'copper',name:'Медь',tag:'Cu',text:'Лом меди, трубы, шины, провода и производственные остатки.'},
 {slug:'aluminium',name:'Алюминий',tag:'Al',text:'Профиль, лист, радиаторы, банки и алюминиевый микс.'},
 {slug:'brass',name:'Латунь',tag:'Br',text:'Арматура, детали, стружка и сантехнические изделия.'},
 {slug:'bronze',name:'Бронза',tag:'Bz',text:'Втулки, детали, подшипники и промышленный лом.'},
 {slug:'stainless-steel',name:'Нержавейка',tag:'SS',text:'Лист, труба, профиль и производственные остатки.'},
 {slug:'lead',name:'Свинец',tag:'Pb',text:'Листовой свинец, грузики и технологические остатки.'},
 {slug:'cable',name:'Кабель',tag:'CAB',text:'Медный и алюминиевый кабель с разными типами оболочки.'},
 {slug:'scrap-steel',name:'Чёрный металл',tag:'Fe',text:'Сталь, железо, конструкции, лист, арматура и профиль.'}
];
const faqs=['От какого объёма можно заказать вывоз?','Как определить вид металла?','Можно ли прислать фотографии для предварительной оценки?','Работаете ли вы с организациями и производствами?','Можно ли заказать демонтаж металлоконструкций?'];

function go(path:string){window.history.pushState({},'',path==='/'?'/':path);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'smooth'});}
function Header(){const [open,setOpen]=useState(false);return <><header className="header"><div className="wrap nav"><button className="brand" onClick={()=>go('/')}><span className="brand-icon"><Recycle size={19}/></span>METAL<span>HUB</span></button><nav><button onClick={()=>go('/metals')}>Металлы</button><button onClick={()=>go('/priem-metalla')}>Приём</button><button onClick={()=>go('/vyvoz-metalla')}>Вывоз</button><button onClick={()=>go('/demontazh')}>Демонтаж</button></nav><a className="phone" href="tel:+78000000000"><Phone size={16}/> 8 800 000-00-00</a><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile-nav"><button onClick={()=>{setOpen(false);go('/metals')}}>Металлы</button><button onClick={()=>{setOpen(false);go('/priem-metalla')}}>Приём</button><button onClick={()=>{setOpen(false);go('/vyvoz-metalla')}}>Вывоз</button><button onClick={()=>{setOpen(false);go('/demontazh')}}>Демонтаж</button><button onClick={()=>{setOpen(false);go('/contact')}}>Контакты</button></div>}</header></>}
function Button({children,onClick,light=false}:{children:any;onClick?:()=>void;light?:boolean}){return <button className={light?'btn btn-light':'btn btn-dark'} onClick={onClick}>{children}<ArrowRight size={17}/></button>}
function Hero(){return <section className="hero"><div className="wrap hero-grid"><div className="hero-copy"><div className="eyebrow"><i/> ПРИЁМ · ВЫВОЗ · ДЕМОНТАЖ</div><h1>Металлолом,<br/><span>который работает</span><br/>на ваш результат.</h1><p>Принимаем цветной и чёрный металл в Санкт-Петербурге и Ленинградской области. Организуем оценку, погрузку и вывоз с объекта.</p><div className="actions"><Button onClick={()=>document.getElementById('quote')?.scrollIntoView({behavior:'smooth'})}>Получить расчёт</Button><button className="text-btn" onClick={()=>go('/metals')}>Смотреть металлы <ArrowRight size={17}/></button></div><div className="hero-points"><span><Check/>Выезд по СПб и ЛО</span><span><Check/>Погрузка и транспорт</span><span><Check/>Для частных лиц и бизнеса</span></div></div><div className="hero-card"><div className="hero-card-top"><span>METAL HUB</span><span>SPB · LO</span></div><div className="metal-orb"><div className="ring ring1"/><div className="ring ring2"/><strong>Cu</strong><small>METAL</small></div><div className="hero-card-bottom"><div><small>Предварительная оценка</small><b>По фото и описанию</b></div><ShieldCheck size={28}/></div></div></div></section>}
function Stats(){return <div className="stats"><div className="wrap stats-grid"><div><b>СПб + ЛО</b><span>география работы</span></div><div><b>8+</b><span>основных категорий</span></div><div><b>24/7</b><span>приём заявок</span></div><div><b>1 шаг</b><span>до заявки на расчёт</span></div></div></div>}
function Services(){return <section className="section"><div className="wrap"><div className="section-head"><div><div className="eyebrow">УСЛУГИ</div><h2>Всё, что нужно<br/>для работы с металлом.</h2></div><p>От небольшого объёма до производственного объекта: выбираете задачу — мы подбираем формат работы.</p></div><div className="services"><article onClick={()=>go('/priem-metalla')}><div className="service-icon"><Recycle/></div><small>01 / ПРИЁМ</small><h3>Приём металлолома</h3><p>Цветной, чёрный металл, кабель и нержавейка. Сортировка по категориям.</p><button>Подробнее <ArrowRight/></button></article><article onClick={()=>go('/vyvoz-metalla')}><div className="service-icon"><Truck/></div><small>02 / ВЫВОЗ</small><h3>Вывоз с объекта</h3><p>Организуем погрузку и транспорт. Условия зависят от объёма и адреса.</p><button>Подробнее <ArrowRight/></button></article><article onClick={()=>go('/demontazh')}><div className="service-icon"><Building2/></div><small>03 / ДЕМОНТАЖ</small><h3>Демонтаж конструкций</h3><p>Металлоконструкции, оборудование и производственные остатки.</p><button>Подробнее <ArrowRight/></button></article></div></div></section>}
function Metals(){return <section className="section metals-section"><div className="wrap"><div className="section-head"><div><div className="eyebrow">КАТАЛОГ</div><h2>Основные виды<br/>металлолома.</h2></div><p>У каждой категории — отдельная страница с описанием, характеристиками и SEO-контентом.</p></div><div className="metal-grid">{metals.map((m,i)=><article className="metal-card" key={m.slug} onClick={()=>go('/'+m.slug)}><div className="metal-number">{String(i+1).padStart(2,'0')}</div><div className="metal-symbol">{m.tag}</div><small>КАТЕГОРИЯ {String(i+1).padStart(2,'0')}</small><h3>{m.name}</h3><p>{m.text}</p><span>Открыть страницу <ArrowRight/></span></article>)}</div></div></section>}
function Process(){return <section className="dark-section"><div className="wrap process-grid"><div><div className="eyebrow light-eyebrow"><i/> КАК ЭТО РАБОТАЕТ</div><h2>Просто от заявки<br/>до результата.</h2><p>Не обещаем цифры, которые нельзя подтвердить. Сначала выясняем тип металла, объём и условия вывоза — затем согласовываем расчёт.</p></div><div className="steps"><div><b>01</b><span><strong>Заявка</strong><small>Фото, адрес, объём и описание.</small></span></div><div><b>02</b><span><strong>Оценка</strong><small>Уточняем категорию и формат работ.</small></span></div><div><b>03</b><span><strong>Выезд</strong><small>Согласовываем время и транспорт.</small></span></div><div><b>04</b><span><strong>Расчёт</strong><small>Финальные условия после проверки материала.</small></span></div></div></div></section>}
function Quote(){const [weight,setWeight]=useState(500);return <section className="section quote-section" id="quote"><div className="wrap quote-grid"><div><div className="eyebrow">РАСЧЁТ</div><h2>Узнайте стоимость своего объёма.</h2><p>Оставьте данные — менеджер сможет уточнить категорию металла, объём, адрес и формат вывоза.</p><div className="quote-list"><span><Check/>Без выдуманных цен</span><span><Check/>Расчёт по конкретному объекту</span><span><Check/>Можно приложить фото</span></div></div><div className="calc"><div className="calc-title"><Calculator/> Предварительный расчёт</div><label>Категория<select><option>Медь</option><option>Алюминий</option><option>Латунь</option><option>Чёрный металл</option><option>Другое</option></select></label><label>Ориентировочный вес <b>{weight.toLocaleString('ru-RU')} кг</b><input type="range" min="100" max="5000" step="100" value={weight} onChange={e=>setWeight(+e.target.value)}/></label><div className="calc-result"><small>Стоимость</small><strong>Уточняется по прайсу</strong></div><Button onClick={()=>document.getElementById('lead')?.scrollIntoView({behavior:'smooth'})}>Получить точный расчёт</Button></div></div></section>}
function Lead(){const [sent,setSent]=useState(false);return <section className="lead" id="lead"><div className="wrap lead-grid"><div><div className="eyebrow">ЗАЯВКА</div><h2>Есть металл?<br/><span>Давайте посчитаем.</span></h2><p>Укажите телефон и несколько деталей. Форма готова к подключению CRM, Telegram или e-mail.</p><div className="lead-bullets"><span><Check/>СПб и Ленинградская область</span><span><Check/>Частные лица и организации</span><span><Check/>Приём, вывоз и демонтаж</span></div></div>{sent?<div className="form success"><Check/><h3>Заявка отправлена</h3><p>Демо-форма работает. Для реальных заявок подключим нужный канал.</p><button onClick={()=>setSent(false)}>Отправить ещё</button></div>:<form className="form" onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-row"><input required placeholder="Имя"/><input required placeholder="Телефон"/></div><input placeholder="Адрес / район"/><textarea rows={4} placeholder="Что сдаёте? Объём, фото и детали"></textarea><button className="btn btn-dark" type="submit">Отправить заявку <ArrowRight/></button><small>Перед публикацией подключите реальные реквизиты, телефон и обработку заявок.</small></form>}</div></section>}
function FAQ(){const [active,setActive]=useState<number|null>(null);return <section className="section"><div className="wrap faq-grid"><div><div className="eyebrow">FAQ</div><h2>Частые вопросы.</h2><p>Информационный блок для посетителей и поисковых систем. Ответы можно расширять по мере развития проекта.</p></div><div className="faq-list">{faqs.map((q,i)=><div className={'faq-item '+(active===i?'open':'')} key={q}><button onClick={()=>setActive(active===i?null:i)}><span>{q}</span><ChevronDown/></button>{active===i&&<p>Условия зависят от типа металла, объёма, адреса и формата работ. Для точного ответа отправьте заявку с описанием или фотографиями.</p>}</div>)}</div></div></section>}
function Footer(){return <footer><div className="wrap footer-grid"><div><button className="brand light" onClick={()=>go('/')}><span className="brand-icon"><Recycle size={18}/></span>METAL<span>HUB</span></button><p>Приём, вывоз и демонтаж металлолома в Санкт-Петербурге и Ленинградской области.</p></div><div><b>Услуги</b><button onClick={()=>go('/priem-metalla')}>Приём металла</button><button onClick={()=>go('/vyvoz-metalla')}>Вывоз металла</button><button onClick={()=>go('/demontazh')}>Демонтаж</button></div><div><b>Металлы</b>{metals.slice(0,4).map(m=><button key={m.slug} onClick={()=>go('/'+m.slug)}>{m.name}</button>)}</div><div><b>Контакты</b><a href="tel:+78000000000">8 800 000-00-00</a><span><MapPin/> Санкт-Петербург и ЛО</span><span>Заявки круглосуточно</span></div></div><div className="wrap copyright">© 2026 Metal Hub · Демо-данные необходимо заменить на реальные перед запуском.</div></footer>}
function Page(){const path=window.location.pathname.replace(/^\//,'').replace(/\/$/,'');const metal=metals.find(m=>m.slug===path);if(metal)return <><Header/><main><section className="inner-hero"><div className="wrap"><div className="eyebrow">КАТЕГОРИЯ МЕТАЛЛА</div><h1>Приём лома<br/><span>{metal.name}</span></h1><p>{metal.text} Подготовьте фотографии и ориентировочный объём — это поможет быстрее определить формат работы.</p><Button onClick={()=>go('/#lead')}>Получить расчёт</Button></div></section><section className="section"><div className="wrap article"><h2>{metal.name}: что принимаем</h2><p>На этой странице размещается подробная информация о разновидностях материала, сортировке, подготовке, погрузке и условиях вывоза. Итоговая стоимость зависит от конкретного вида, чистоты, объёма и действующего прайса.</p><h2>Как подготовить металл</h2><p>Если есть возможность, разделите разные материалы и уберите очевидные посторонние примеси. Для кабеля, радиаторов и смешанного лома полезно прислать несколько фотографий крупным планом.</p><h2>Вывоз из Санкт-Петербурга и ЛО</h2><p>При заявке укажите адрес, объём и удобное время. После уточнения деталей можно определить транспорт, погрузку и порядок работы.</p></div></section><Lead/></main><Footer/></>;return <><Header/><main><Hero/><Stats/><Services/><Metals/><Process/><Quote/><FAQ/><Lead/></main><Footer/></>}
function App(){return <Page/>}
export default App;
