import { createRoot } from 'react-dom/client';
import { useEffect, useState } from 'react';
import { ArrowRight, Check, ChevronDown, Menu, Phone, Truck, Scale, Factory, Recycle, MapPin, Clock3, ShieldCheck, X } from 'lucide-react';
import './styles.css';

const phone = '+7 (900) 123-45-67';
const heroImg = 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1800&q=85';
const truckImg = 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1200&q=85';
const demoImg = 'https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&w=1200&q=85';
const metalImg = 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=85';

const metals = [
  ['Медь','720 ₽','/metall/med'],['Алюминий','120 ₽','/metall/alum'],['Латунь','440 ₽','/metall/latun'],['Бронза','360 ₽','/metall/bronz'],['Свинец','160 ₽','/metall/svinec'],['Нержавейка','160 ₽','/metall/nerzh'],['Кабель','570 ₽','/metall/kabel'],['Чёрный металл','25 ₽','/metall/chermet']
];
const services = [
  ['Приём меди','Высокая цена, честное взвешивание и быстрый расчёт.','/metall/med'],
  ['Приём алюминия','Принимаем алюминиевый профиль, лист, лом и изделия.','/metall/alum'],
  ['Приём кабеля','Медный и алюминиевый кабель, силовой и бытовой.','/metall/kabel'],
  ['Приём латуни и бронзы','Сортировка и оценка цветного металла.','/metall/latun'],
  ['Приём чёрного металла','Сталь, железо, конструкции и производственный лом.','/metall/chermet'],
  ['Самовывоз металла','Газели, КамАЗы и манипуляторы по СПб и ЛО.','/samovyvoz'],
  ['Демонтаж зданий','Разборка зданий, цехов, ангаров и сооружений.','/demontazh'],
  ['Демонтаж конструкций','Резка и демонтаж металлоконструкций.','/demontazh'],
  ['Разборка оборудования','Демонтаж оборудования с вывозом металлолома.','/uslugi'],
  ['Резка металла','Подготовка крупногабаритного лома к вывозу.','/uslugi']
];
const faq = ['Как заказать самовывоз?','Как происходит взвешивание?','Принимаете ли вы кабель?','Работаете ли с организациями?','Делаете ли демонтаж на объекте?','Работаете ли по Ленинградской области?'];

function go(path:string){ history.pushState({},'',path); window.dispatchEvent(new PopStateEvent('popstate')); window.scrollTo({top:0,behavior:'smooth'}); }
function Link({to,children,className=''}:{to:string;children:any;className?:string}){ return <a href={to} className={className} onClick={e=>{e.preventDefault();go(to)}}>{children}</a> }
function Logo(){return <Link to="/" className="brand"><span className="brandMark">АМ</span><span>ДемонтажМеталл<span>Инвест</span><small>ПРИЁМ • ПЕРЕРАБОТКА • ВТОРИЧНЫЕ РЕСУРСЫ</small></span></Link>}

function Header(){const [open,setOpen]=useState(false); const nav=[['Главная','/'],['Услуги','/uslugi'],['Цены','/ceny'],['О компании','/o-kompanii'],['Контакты','/kontakty']]; return <header className="header"><div className="wrap nav"><Logo/><nav>{nav.map(([n,p])=><Link key={p} to={p}>{n}</Link>)}</nav><div className="headContact"><Phone/><div><b>{phone}</b><small>Звоните с 8:00 до 20:00</small></div></div><Link to="/kontakty" className="orangeBtn">Заказать звонок</Link><button className="hamb" onClick={()=>setOpen(!open)} aria-label="Меню">{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile"><div className="wrap">{nav.map(([n,p])=><Link key={p} to={p} onClick={()=>setOpen(false)}>{n}</Link>)}</div></div>}</header>}

function Hero(){return <section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(3,12,17,.94),rgba(3,12,17,.45)),url(${heroImg})`}}><div className="wrap heroContent"><div className="eyebrow">МЕТАЛЛОЛОМНАЯ КОМПАНИЯ</div><h1>ДемонтажМеталл<span>Инвест</span></h1><p>Приём металла. Демонтаж конструкций. Вывоз. Быстро. Надёжно.</p><div className="heroBenefits"><div><Scale/>Высокие цены<br/>за ваш металл</div><div><ShieldCheck/>Честный вес<br/>и расчёт</div><div><Truck/>Быстрый вывоз<br/>и демонтаж</div><div><MapPin/>Работаем по СПб<br/>и области</div></div><div className="actions"><Link to="/ceny" className="orangeBtn">Узнать цены <ArrowRight/></Link><Link to="/o-kompanii" className="ghostBtn">О компании</Link></div></div></section>}

function LeadForm(){const [sent,setSent]=useState(false); return sent?<div className="success"><Check/><h3>Заявка отправлена</h3><p>Спасибо! Мы свяжемся с вами и уточним детали.</p></div>:<form className="leadForm" onSubmit={e=>{e.preventDefault();setSent(true)}}><input required placeholder="Ваше имя"/><input required placeholder="Телефон"/><select defaultValue=""><option value="" disabled>Что сдаёте?</option><option>Медь</option><option>Алюминий</option><option>Кабель</option><option>Чёрный металл</option><option>Демонтаж</option></select><input placeholder="Примерный объём"/><textarea placeholder="Адрес и комментарий" rows={3}/><button className="orangeBtn">Получить предложение <ArrowRight/></button></form>}

function MetalCards(){return <div className="metalGrid">{metals.slice(0,6).map(([name,price,path],i)=><Link to={path} key={name} className="metalCard" style={{backgroundImage:`linear-gradient(0deg,rgba(2,10,14,.92),rgba(2,10,14,.1)),url(${[metalImg,truckImg,heroImg,metalImg,demoImg,heroImg][i]})`}}><div><b>{name}</b><span>от {price}/кг</span></div><i><ArrowRight/></i></Link>)}</div>}

function Home(){return <><Hero/><section className="section darkSection"><div className="wrap"><div className="sectionHead"><div><div className="eyebrow">ПРИЁМ МЕТАЛЛА</div><h2>Сдайте металл — получите деньги!</h2><p>Принимаем цветные и чёрные металлы по прозрачным условиям. Честный вес и расчёт.</p></div><Link to="/ceny" className="outlineBtn">Актуальные цены <ArrowRight/></Link></div><MetalCards/></div></section><section className="splitServices"><div className="serviceFeature" style={{backgroundImage:`linear-gradient(90deg,rgba(2,10,14,.95),rgba(2,10,14,.2)),url(${truckImg})`}}><div><div className="eyebrow">ДОПОЛНИТЕЛЬНЫЕ УСЛУГИ</div><h2>Самовывоз металла</h2><p>Собственный автопарк. Оперативный вывоз любых объёмов металлолома по Санкт-Петербургу и области.</p><ul><li>Газели, КамАЗы, манипуляторы</li><li>Работа по городу и области</li><li>Вывоз любых объёмов</li></ul><Link to="/samovyvoz" className="orangeBtn">Заказать вывоз <ArrowRight/></Link></div></div><div className="serviceFeature" style={{backgroundImage:`linear-gradient(90deg,rgba(2,10,14,.95),rgba(2,10,14,.2)),url(${demoImg})`}}><div><div className="eyebrow">ДОПОЛНИТЕЛЬНЫЕ УСЛУГИ</div><h2>Демонтаж любых конструкций</h2><p>Профессиональный демонтаж зданий, сооружений, ангаров, цехов и других объектов.</p><ul><li>Любая сложность</li><li>Собственная техника</li><li>Вывоз мусора и металлолома</li></ul><Link to="/demontazh" className="orangeBtn">Заказать демонтаж <ArrowRight/></Link></div></div></section><Why/><section className="aboutStrip"><div className="wrap aboutGrid"><img src={demoImg} alt="Демонтаж и переработка металла"/><div><div className="eyebrow">О КОМПАНИИ</div><h2>ДемонтажМеталл<span>Инвест</span></h2><p>Надёжный партнёр в сфере приёма и переработки металлолома, демонтажа конструкций и вывоза металла.</p><div className="stats"><b>5+<small>лет на рынке</small></b><b>1000+<small>клиентов</small></b><b>50+<small>единиц техники</small></b></div></div><div className="formCard"><h3>Оставьте заявку</h3><p>И получите индивидуальные условия</p><LeadForm/></div></div></section><section className="section light"><div className="wrap"><div className="sectionHead"><div><div className="eyebrow">КАК МЫ РАБОТАЕМ</div><h2>От заявки до расчёта — 4 шага</h2></div></div><div className="steps">{[['01','Заявка','Оставляете телефон или звоните нам.'],['02','Оценка','Определяем вид и объём металла.'],['03','Вывоз','Приезжаем на объект своим транспортом.'],['04','Расчёт','Взвешиваем металл и производим расчёт.']].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section><Reviews/><FAQ/><CTA/></>}

function Why(){return <section className="why"><div className="wrap"><div className="eyebrow">ПОЧЕМУ ВЫБИРАЮТ НАС</div><div className="whyGrid">{[[Scale,'Высокие закупочные цены','Предлагаем конкурентные цены на рынке.'],[ShieldCheck,'Честный вес','Современные весы и прозрачный расчёт.'],[Clock3,'Оперативность','Быстрый вывоз и демонтаж.'],[Truck,'Собственный транспорт','Свой автопарк для вывоза металла.'],[Factory,'Профессиональная команда','Опытные специалисты и техника.'],[Recycle,'Забота об экологии','Переработка вторичного сырья.']].map(([I,t,d])=><div key={t}><I/><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>}
function Reviews(){return <section className="reviews"><div className="wrap"><div className="eyebrow">ОТЗЫВЫ КЛИЕНТОВ</div><div className="reviewGrid">{['Алексей Петров','Ирина Соколова','Дмитрий Кузнецов'].map((n,i)=><article key={n}><b>{n}</b><small>{['Санкт-Петербург','Ленинградская область','СПб'][i]}</small><p>{['Оперативный вывоз, быстро приняли технику, выдали расчёт.','Вежливые сотрудники, честный вес, хорошие условия.','Всё чётко и организованно. Спасибо за профессиональную работу.'][i]}</p><span>★★★★★</span></article>)}</div></div></section>}
function FAQ(){const [open,setOpen]=useState<number|null>(null); return <section className="section light"><div className="wrap narrow"><div className="eyebrow">ЧАСТО ЗАДАВАЕМЫЕ ВОПРОСЫ</div><h2>Ответы на популярные вопросы</h2>{faq.map((q,i)=><div className="faq" key={q}><button onClick={()=>setOpen(open===i?null:i)}><b>{q}</b><ChevronDown/></button>{open===i&&<p>Оставьте заявку или позвоните нам. Специалист уточнит вид металла, объём, адрес и согласует удобное время. Условия зависят от вида сырья и объёма.</p>}</div>)}</div></section>}
function CTA(){return <section className="cta" style={{backgroundImage:`linear-gradient(90deg,rgba(2,10,14,.96),rgba(2,10,14,.55)),url(${heroImg})`}}><div className="wrap ctaGrid"><div><div className="eyebrow">ОСТАЛИСЬ ВОПРОСЫ?</div><h2>Получите расчёт и условия</h2><p>Оставьте заявку — перезвоним и обсудим задачу.</p></div><Link to="/kontakty" className="orangeBtn">Заказать звонок <ArrowRight/></Link></div></section>}

function PageHero({title,sub}:{title:string;sub:string}){return <section className="pageHero" style={{backgroundImage:`linear-gradient(90deg,rgba(2,10,14,.94),rgba(2,10,14,.55)),url(${heroImg})`}}><div className="wrap"><div className="eyebrow">ДЕМОНТАЖМЕТАЛЛИНВЕСТ</div><h1>{title}</h1><p>{sub}</p></div></section>}
function ServicesPage(){return <><PageHero title="Услуги" sub="Приём металла, самовывоз, демонтаж и переработка вторичного сырья."/><section className="section light"><div className="wrap"><div className="serviceLargeGrid">{services.map(([t,d,p],i)=><article key={t}><span>{String(i+1).padStart(2,'0')}</span><h2>{t}</h2><p>{d}</p><Link to={p}>Подробнее <ArrowRight/></Link></article>)}</div></div></section><CTA/></>}
function PricesPage(){return <><PageHero title="Цены на металлолом" sub="Актуальные цены зависят от вида, качества, объёма и условий вывоза."/><section className="section light"><div className="wrap"><div className="priceTable">{metals.map(([m,p])=><div key={m}><b>{m}</b><span>{p} / кг</span><span>{p} 000 / тонна</span><em>Уточнить условия</em></div>)}</div><div className="priceNote">Цены на сайте являются ориентиром. Перед сдачей уточните актуальную стоимость по телефону.</div></div></section><CTA/></>}
function PickupPage(){return <><PageHero title="Самовывоз металла" sub="Собственный транспорт и оперативный вывоз по Санкт-Петербургу и Ленинградской области."/><section className="featurePage"><div className="wrap featureGrid"><img src={truckImg} alt="Самовывоз металла"/><div><div className="eyebrow">ВЫВОЗ МЕТАЛЛОЛОМА</div><h2>Приезжаем на объект своим транспортом</h2><p>Организуем вывоз небольших и крупных объёмов. Подбираем транспорт под задачу и согласуем время.</p><ul><li>Газели</li><li>КамАЗы</li><li>Манипуляторы</li><li>Работа по СПб и ЛО</li><li>Вывоз любых объёмов</li></ul><Link to="/kontakty" className="orangeBtn">Заказать вывоз <ArrowRight/></Link></div></div></section><CTA/></>}
function DemoPage(){return <><PageHero title="Демонтаж конструкций" sub="Профессиональный демонтаж зданий, сооружений, ангаров, цехов и металлоконструкций."/><section className="featurePage"><div className="wrap featureGrid"><div><div className="eyebrow">ДЕМОНТАЖ</div><h2>Разбираем объекты любой сложности</h2><p>Проводим демонтаж с собственной техникой, организуем погрузку и вывоз металлолома и строительного мусора.</p><ul><li>Демонтаж зданий и сооружений</li><li>Демонтаж металлоконструкций</li><li>Резка металла</li><li>Разборка оборудования</li><li>Вывоз металлолома</li></ul><Link to="/kontakty" className="orangeBtn">Рассчитать демонтаж <ArrowRight/></Link></div><img src={demoImg} alt="Демонтаж конструкций"/></div></section><CTA/></>}
function AboutPage(){return <><PageHero title="О компании" sub="Приём и переработка металла, демонтаж конструкций и вывоз вторичного сырья."/><section className="section light"><div className="wrap aboutLong"><img src={demoImg} alt="ДемонтажМеталлИнвест"/><div><div className="eyebrow">ДЕМОНТАЖМЕТАЛЛИНВЕСТ</div><h2>Работаем на результат и чистое будущее</h2><p>Мы организуем приём металлолома, демонтаж конструкций и вывоз сырья. Работаем с частными клиентами, организациями и объектами в Санкт-Петербурге и Ленинградской области.</p><div className="stats"><b>5+<small>лет на рынке</small></b><b>1000+<small>клиентов</small></b><b>50+<small>единиц техники</small></b></div></div></div></section><Why/><CTA/></>}
function ContactsPage(){return <><PageHero title="Контакты" sub="Оставьте заявку или позвоните — согласуем условия и удобное время."/><section className="section light"><div className="wrap contactPage"><div className="contactInfo"><h2>Свяжитесь с нами</h2><a href={`tel:${phone.replace(/[^0-9+]/g,'')}`}><Phone/> {phone}</a><p><MapPin/> Санкт-Петербург и Ленинградская область</p><p><Clock3/> Ежедневно, 8:00–20:00</p><div className="map">Санкт-Петербург<br/><small>Карта и точный адрес уточняются при заявке</small></div></div><div className="formCard"><h3>Оставьте заявку</h3><p>И получите индивидуальные условия</p><LeadForm/></div></div></section></>}
function MetalPage({name,price}:{name:string;price:string}){return <><PageHero title={`Приём ${name.toLowerCase()} в Санкт-Петербурге`} sub={`Принимаем ${name.toLowerCase()} с честным взвешиванием и расчётом. Ориентир цены — ${price}/кг.`}/><section className="featurePage"><div className="wrap featureGrid"><img src={metalImg} alt={`Приём ${name}`}/><div><div className="eyebrow">ПРИЁМ {name.toUpperCase()}</div><h2>Сдайте {name.toLowerCase()} выгодно</h2><p>Принимаем лом у частных лиц и организаций. Стоимость зависит от качества, засора, объёма и условий вывоза.</p><div className="bigPrice">от {price}<small>за кг</small></div><Link to="/kontakty" className="orangeBtn">Узнать точную цену <ArrowRight/></Link></div></div></section><section className="section light"><div className="wrap"><h2>Как проходит приём</h2><div className="steps">{[['01','Заявка','Отправьте заявку или позвоните.'],['02','Оценка','Уточним вид и объём металла.'],['03','Взвешивание','Проверяем массу на весах.'],['04','Расчёт','Производим расчёт по согласованной цене.']].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section><CTA/></>}

function App(){const [path,setPath]=useState(location.pathname); useEffect(()=>{const f=()=>setPath(location.pathname); addEventListener('popstate',f); return()=>removeEventListener('popstate',f)},[]); let content:any=<Home/>; if(path==='/uslugi')content=<ServicesPage/>; else if(path==='/ceny')content=<PricesPage/>; else if(path==='/samovyvoz')content=<PickupPage/>; else if(path==='/demontazh')content=<DemoPage/>; else if(path==='/o-kompanii')content=<AboutPage/>; else if(path==='/kontakty')content=<ContactsPage/>; else if(path.startsWith('/metall/')){const key=path.split('/')[2]; const map:any={med:['меди','720 ₽'],alum:['алюминия','120 ₽'],latun:['латуни','440 ₽'],bronz:['бронзы','360 ₽'],svinec:['свинца','160 ₽'],nerzh:['нержавейки','160 ₽'],kabel:['медного кабеля','570 ₽'],chermet:['чёрного металла','25 ₽']}; const d=map[key]||map.med; content=<MetalPage name={d[0]} price={d[1]}/>;} return <><Header/><main>{content}</main><footer><div className="wrap footer"><Logo/><div><Link to="/uslugi">Услуги</Link><Link to="/ceny">Цены</Link><Link to="/o-kompanii">О компании</Link><Link to="/kontakty">Контакты</Link></div><div className="footerPhone">{phone}<small>Металлолом — это не мусор, это ресурс!</small></div></div></footer></>}

createRoot(document.getElementById('root')!).render(<App/>);
